---
name: Checks

#creating a trigger for the workflow to run on push events
on: [push]

jobs:
#finds new job called test-lint (we see in github action interface) 
#runner is os that we use to run job on here we are using ubuntu-20.04
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-24.04
    steps:
#this step checks out the repository so that we can access the code
#pushing code to github to check activity
      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Check out repository code
        uses: actions/checkout@v2
#this checkout is action by github as we need to run test and linting on code 
      - name: Checkout
        uses: actions/setup-python@v2
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"